/* generated by Makefile */
#define TOP_SRC_DIR ".."
#define LIBRARY_DIR "/usr/local/lib"
#define PKGDATA_DIR "/usr/local/share/turtle"
#define SITE_DIR "/usr/local/share/turtle/site"
#define MODULE_DIR "/usr/local/lib/turtle/1.0.0"
#define INCLUDE_DIR "/usr/local/include"
