/* generated by Makefile */
#define TOP_SRC_DIR ".."
#define LIBRARY_DIR "/home/mgrabmue/diplom/x/lib"
#define PKGDATA_DIR "/home/mgrabmue/diplom/x/share/turtle"
#define SITE_DIR "/home/mgrabmue/diplom/x/share/turtle/site"
#define MODULE_DIR "/home/mgrabmue/diplom/x/lib/turtle/1.0.0"
#define INCLUDE_DIR "/home/mgrabmue/diplom/x/include"
